version: '3.9'

services:
  payment:
    container_name: be-payment
    image: be-payment
    restart: always
    depends_on:
      - mongodb
    env_file: ./.env
    ports:
      - ${PORT}:${PORT}
  mongodb:
    image: docker.io/bitnami/mongodb:5.0
    environment:
      - MONGODB_ROOT_PASSWORD=${DB_MONGO_PASSWORD}
    volumes:
      - 'mongodb:/bitnami/mongodb'
    ports:
      - '${DB_MONGO_PORT}:27017'
volumes:
  mongodb:
    driver: local
